### ISSUE TITLE
Request: Icons for TETR.IO, osu!/osu!lazer, and LabyMod

### ISSUE THREAD

**Issue by Pineappman3102** [dreifacherspass/cyberpunk-technotronic-icon-theme#13]
Hello, I'd just like to request icons for TETR.IO, osu!/osu!lazer, and LabyMod. It seems these games don't have icons, unless I've missed them. 

Here's the branding info for each, which includes the logos.
TETR.IO - https://txt.osk.sh/branding/
osu! - https://osu.ppy.sh/wiki/en/Brand_identity_guidelines (I don't mind if it's reused for osu!lazer)
LabyMod - https://www.labymod.net/en/branding

Thanks for the great icon theme by the way, it goes great with my synthwave-themed setup.

**Comment by dreifacherspass** [comment]
Hello! The icons are ready and will be included in the next update on pling.
Thank you for your kind words! Enjoy!
