### ISSUE TITLE
request: icon Request (Librewolf, Mullvad Browser)

### ISSUE THREAD

**Issue by 1tituz** [dreifacherspass/cyberpunk-technotronic-icon-theme#14]
Thanks for the great icon set!
If you find some time, icons for the Browsers Librewolf and Mullvad would be a great addition.
thx!!

**Comment by dreifacherspass** [comment]
You are welcome!
The icons are ready and will be included in the next update on pling.
Enjoy.

**Comment by 1tituz** [comment]
Thanks a lot!

**Comment by dreifacherspass** [comment]
You are welcome! I hope you like the new icons. Thanks for reporting the missing ones.
