### ISSUE TITLE
Gradient base?

### ISSUE THREAD

**Issue by ravengalqueen** [dreifacherspass/cyberpunk-technotronic-icon-theme#15]
Hello, is it possible to get the source gradient base so people can make their own icons?

**Comment by dreifacherspass** [comment]
I am sorry but I didn't have the time to answer earlier. The icons are in svg format and the source code is open. Just use your favourite design tool or just a text editor.

Since you closed this as completed I suppose you found what you are looking for. If not, then please ask again.
