### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by D-Chatzis** [dreifacherspass/cyberpunk-technotronic-icon-theme#16]
Hello, 
It would be nice if you could add these icons as well
Vscode, Plex, PlexAmp, betterBird , PureRef

Thanks!

**Comment by TheWyn** [comment]
Discord tray icons as well please

Thanks

![image](https://github.com/user-attachments/assets/deacd8db-4b3b-4d0a-a72e-7839d8c2b18e)

**Comment by dreifacherspass** [comment]
@D-Chatzis Thank you for reporting the missing icons. The icons are ready and will be included in the next update. The plex and plexamp icons were already in the icon pack. If they still don't appear, let me know.

@TheWyn Thank you for your message. This is a known issue. The tray icons are in the icon pack but discord doesn't use them. It has been reported on many forums and on my product page (see the comment section at https://www.pling.com/p/1999292). I will check if something's changed. It would be better to contact the developers of discord.
