### ISSUE TITLE
More a request.

### ISSUE THREAD

**Issue by triantares** [dreifacherspass/cyberpunk-technotronic-icon-theme#2]
Hello @dreifacherspass,
On Elive Linux we're working on a special 'RetroWave' release and I would like to add your iconset there.
Personally I'd love to make it the default icon set but there are some caveats there. The biggest is the 'folder.svg' which has a lesser effect in directories/folders with multiple sub-folders. It gets too massive and we're looking to change or replace it along the lines of sweet/candy or BeautyLine i.e a more open design.

Currently we're aiming for BeautyLine ( https://gitlab.com/Elive/beautyline-icons ) and we've made some changes/additions there to accommodate Enlightenment E16.
We even used some of your icons there (inkscape, unison ) and added some of our own.
The question is:
Should we create a branch for ourselves and make the changes there and offer them as 'merges' or would you prefer to do it yourself?
  Point is that I (me personally) have a strong preference for 'gitlab' and I'm the one doing the changes. :innocent:

**Comment by dreifacherspass** [comment]
Hello @triantares, 
I am happy to know that you like my iconset and that you are thinking of including it in the RetroWave release.

If I understand correctly you don't like the effect of filled folders and you would rather have just the outline.
Is this better?  
e407f3fccaf90c8b21eecba27909a4bd2a153514


I could do the changes myself.
