### ISSUE TITLE
default icon size for bitmap rendering

### ISSUE THREAD

**Issue by triantares** [dreifacherspass/cyberpunk-technotronic-icon-theme#3]
When using icons in 'tint2' as large as 56 they are rendered pixelized/fuzzy.
https://i.imgur.com/QmMAiYQ.png
This is definetely down to tint2 rendering  i.e not scaling the vector.
On top they render extremely small in the file preview (thunar here), smaller than the link symbol. 
To view in 'viewnior' requires enormous zooming. :(
https://i.imgur.com/cxUJwCl.png

This is because they render PNGs from the size set there, i.e 16 and is where in fact all links  point to.

I think it would be better to save/link to a larger size like 64 or 128 and work from there. :thinking:

**Comment by dreifacherspass** [comment]
This means that all the icons have to be modified. That would take a lot of effort. The iconset has around 1600 icons only in the /apps/16 folder. 

Since this is an issue with tint2, I think it would be better to ask from its developers to change the way the icons are rendered. 

The taskbars/panels of Plasma, Gnome and XFCE upscale the icons correctly.

The rendering issue in viewnior, I don't consider it a problem. The icon theme is not supposed to be a gallery of pictures. I don't think users browse the iconsets. 

As far as thunar is concerned, I tried it myself and there is no scaling issue. The icons are rendered correctly, no matter how much I zoom them in.

The biggest problem is the rendering of tint2 and I think it can be solved by using another taskbar/launcher that is actively developed.

**Comment by triantares** [comment]
> The iconset has around 1600 icons only in the /apps/16 folder.

I made a count a while back: 10025 files not counting symlinks :)
including symlinks: 25432 files

> As far as thunar is concerned, I tried it myself and there is no scaling issue. The icons are rendered correctly, no matter how much I zoom them in.

It might be related to my laptop which has an 11inch screen at 2560x1440 , so 16 px icons are quite small but could also be related to how E16 renders vectors.
I'm on holiday ATM so I cannot check on other machines. :)

Anyway, the issue (if it's that at all) is down to the metadata set with the icon.svg file and are easily changed using a script ...... I think. :thinking:  I tried to do a quicky (and dirty) this morning but am getting stuck by the script as it creates .svg files from the symlinks too. Once I can exclude those consistently it'll be easy enough.
Anyway trhe default dock for Elive RetroWave is cairo-dock and that renders fine, so there's no real problem there.

**Comment by triantares** [comment]
> As far as thunar is concerned, I tried it myself and there is no scaling issue.

Be aware that I'm not talking about the rendering of the local icons in the folders but when viewing the 16/ folders in the cloned repo or in /usr/share/icons/cyberpunk.../ or ~/.local/share/icons/cyberpunk-tech.../

**Comment by dreifacherspass** [comment]
> Anyway, the issue (if it's that at all) is down to the metadata set with the icon.svg file and are easily changed using a script ...... I think. thinking I tried to do a quicky (and dirty) this morning but am getting stuck by the script as it creates .svg files from the symlinks too.

Even if you tried to change the size of the icon with a script, you wouldn't have a bigger icon. You would have a bigger canvas but the drawing of the icon would remain the same size and positioned top-left. The end result would be a disaster. Just look at the firefox icon in the following link  [https://imgur.com/a/ANxWiOo](https://imgur.com/a/ANxWiOo)

The script and the symlinks is the easiest part. I could do it for you but you won't have the result that you want.


> Why do have this directory structure?

The directory structure is as comprehensible as possible to accommodate many different environments. My question: Does that create a problem?


> Be aware that I'm not talking about the rendering of the local icons in the folders but when viewing the 16/ folders in the cloned repo or in /usr/share/icons/cyberpunk.../ or ~/.local/share/icons/cyberpunk-tech.../

I haven't tested. But even if this happens, why is it an issue? What's the use of browsing icons with your file manager?

**Comment by triantares** [comment]
> As far as thunar is concerned, I tried it myself and there is no scaling issue.

Be aware that I'm not talking about the rendering of the local icons in the folders but when viewing the 16/ folders in the cloned repo or in /usr/share/icons/cyberpunk.../ or ~/.local/share/icons/cyberpunk-tech.../

**Comment by triantares** [comment]
> What's the use of browsing icons with your file manager?

Well simply to find out what's there and what they look like in an easy fashion. Any customizer will want to do that.
If you right-click on an icon and look at properties -> image you'll see the default size set for bitmap rendering.

**Comment by triantares** [comment]
> Just look at the firefox icon in the following link https://imgur.com/a/ANxWiOo
That looks bad, indeed.

How/what did you change?

I only used` i.e  ' rsvg-convert folder.svg -w 128 -h 128 -f svg -o folder-large.svg ' to make it larger as bitmap and don't see that making any further changes to the file content itself. 
But it's not a a real issue that I can't overcome ..... just leave it al "as is" if you prefer and I'll experiment on an own branch.

**Comment by dreifacherspass** [comment]
> Well simply to find out what's [...] set for bitmap rendering.

If this is the way you are working, that's fine. But saying that icon designers all work the same way as you do, that's a sweeping statement. 

>No not really, only makes making small changes and then committing them to git a bit of a pain .... as you need to navigate to the top directory every-time to commit.

What?! You don't have to go to the top directory. If you are happy working like this, be my guest. Do you think it is advisable to change the directory structure to accommodate your way of working and  at the same time break compatibility with several environments? 

> I only used` i.e ' rsvg-convert folder.svg -w 128 -h 128 -f svg -o folder-large.svg ' to make it larger as bitmap and don't see that making any further changes to the file content itself.

Yes it changed the content. It has removed all the gradients.


In my first message I told you that I could do the changes you wanted. I may have spoken prematurely. I am happy to include icons that you request in my iconset. Other than that I cannot change things just be because you have a different point of view.

**Comment by triantares** [comment]
> Do you think it is advisable to change the directory structure to accommodate your way of working

Not at all.
I was merely wondering why you organized in the way you did and compared to how others do. I actually expected it to be an inheritance from the Ultimate-Punk-Suru set.

> t saying that icon designers all work the same way as you do, that's a sweeping statement.

I think you're misunderstanding me here.
I didn't say I was an icon designer ..... I'm a customizer at most and looking to find icon sets befitting the themes intended for use with elive retrowave, in this case. Skimming the icon set first is simply just what I find fastest.

I wasn't in any way asking for changes, just sharing my thoughts as to why 'tint2' renders badly.

**Comment by dreifacherspass** [comment]
>  I was merely wondering why you organized in the way you did and compared to how others do. I actually expected it to be an inheritance from the Ultimate-Punk-Suru set.

The inheritance that is used in index.theme is a fallback, in case the iconset doesn't have an icon. I don't understand what that has to do with the directory structure of the iconset. 

Actually, the suru icon themes you mentioned, use the same structure that you see in my icon theme.

> Skimming the icon set first is simply just what I find fastest.

If I were you, I would use a proper image viewer, e.g. Gwenview in Plasma does the job.

> I wasn't in any way asking for changes, just sharing my thoughts as to why 'tint2' renders badly.

I think we covered that... that is a problem of tint2.

I am willing to help you as much as I can. But all the things you asked can be solved just by changing the apps you are using.

If you want to use the icon set in elive retrowave, you won't have functionality issues. Of course, if you are using the tint2 panel then you had better contact its developers.

**Comment by triantares** [comment]
Created a fork for Elive with upstream source as of commit d7d97e4 where directories are simplified and bitmap size set to 64x64.
https://gitlab.com/Elive/cyberpunk-technology-icons


I had 2 errors on missing gradients in 'status/scalable' and 1 in 'mimetypes/scalable' saying "inkscape not defined". 
Other then that they work fine on Elive (up to now ... definitely gonna be issues)

Any thoughts?

**Comment by dreifacherspass** [comment]
You opened an issue here and you are asking for help about the code in your repo?!

**Comment by triantares** [comment]
I don't need help, thanks. :)

Do you want the script I used for resizing?
