### ISSUE TITLE
Missing icons for Ardour 6 and 7.

### ISSUE THREAD

**Issue by AxerTheAxe** [dreifacherspass/cyberpunk-technotronic-icon-theme#4]
Hi, it seems the icon pack is missing icons for some newer versions or Ardour. For example, Ardour7 is the latest version on my distribution and it uses its own icon separate from the icon pack. I have just changed the icon in my DE's menu editor to the icon for an older Ardour version for a quick temporary solution but I believe that adding icons for the newer versions would be a good addition. Thanks!

**Comment by dreifacherspass** [comment]
You are welcome. The fix will be included in the next update. Thank you for reporting the missing icons. :-)

**Comment by AxerTheAxe** [comment]
Thanks!
