### ISSUE TITLE
Krita uses generic icon.

### ISSUE THREAD

**Issue by AxerTheAxe** [dreifacherspass/cyberpunk-technotronic-icon-theme#5]
Hello again, it seems that Krita uses the generic paintbrush icon, which can get quite confusing. It seems that you do have a unique icon for Krita but it is not used.

Here are some example images with Krita and Plasma Global Theme both using the same generic icon:
![Screenshot_20230622_162839](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/assets/99703210/30892f9e-0fba-4670-82f3-49c7bd10e8fe)

![Screenshot_20230622_162905](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/assets/99703210/202ed1a3-2144-4f0b-8577-846aab181ce9)

Thanks!

**Comment by dreifacherspass** [comment]
Hello! Yes, you are right. It is confusing. Thank you for reporting.

I see in the images that generic icons are also used for cuttlefish and hamachi.

The next update will include icons for Krita, Cuttlefish and Hamachi.

**Comment by AxerTheAxe** [comment]
Thank you!

**Comment by AxerTheAxe** [comment]
Hi, I would just like to mention that after downloading the new update from KDE discover, the icon for Krita did not update properly, and the issue persisted after reboots. When I searched through the the theme only the old Krita icons were listed and not the [new Krita icon](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/commit/4cd72b919e19d9f29f49a84bf842252287771fb6). However, deleting and reinstalling the icon theme fixed the issue. This only occurred with Krita and other icons added in the update such as Lutris, Cuttlefush, and Hamachi all updated correctly.

Sorry to bug you again and my apologies if none of this is relevant and is just a weird one off bug I just wanted to bring this to your attention. The icons looks amazing as always and I am impressed with the dedication that you put towards everything. Feel free to close this issue if you find that this is not of concern.

**Comment by dreifacherspass** [comment]
Hello! No, you don't bother me at all. Your input is valuable and I am happy to help.

I know that this happens and I have found a workaround. You don't have to log off, delete, reinstall or reboot. Just delete the KDE icon cache: /home/<username>/.cache/icon-cache.kcache

Thank you for your kind words. Don't hesitate to contact me, if there are any issues.

**Comment by AxerTheAxe** [comment]
> Hello! No, you don't bother me at all. Your input is valuable and I am happy to help.
> 
> I know that this happens and I have found a workaround. You don't have to log off, delete, reinstall or reboot. Just delete the KDE icon cache: /home/[username]/.cache/icon-cache.kcache
> 
> Thank you for your kind words. Don't hesitate to contact me, if there are any issues.

Thank you!
