### ISSUE TITLE
Request: Icons for Prism Launcher and Cemu.

### ISSUE THREAD

**Issue by AxerTheAxe** [dreifacherspass/cyberpunk-technotronic-icon-theme#6]
Hi, I would like to request icons for Prism Launcher and Cemu. Both of the apps are packaged in Flatpaks and AppImages. I do not know how those formats handle icons so I will try to provide as much information as possible. I extracted the AppImages for both programs and will provide the relevant information below.

Prism Launcher .desktop:

[Desktop Entry]
Version=1.0
Name=Prism Launcher
Comment=A custom launcher for Minecraft that allows you to easily manage multiple installations of Minecraft at once.
Type=Application
Terminal=false
Exec=prismlauncher
StartupNotify=true
Icon=org.prismlauncher.PrismLauncher
Categories=Game;ActionGame;AdventureGame;Simulation;
Keywords=game;minecraft;mc;
StartupWMClass=PrismLauncher
MimeType=application/zip;application/x-modrinth-modpack+zip
X-AppImage-Version=bfe7e3a

Contains `org.prismlauncher.PrismLauncher.svg` in the AppImages root directory which points to `usr/share/icons/hicolor/scalable/apps/org.prismlauncher.PrismLauncher.svg`

Cemu .desktop:

[Desktop Entry]
Name=Cemu
Type=Application
Terminal=false
Icon=info.cemu.Cemu
Exec=Cemu
GenericName=Wii U Emulator
GenericName[fi]=Wii U -emulaattori
GenericName[el]=Πρόγραμμα προσομοίωσης Wii U
GenericName[es]=Emulador de Wii U
GenericName[pt_BR]=Emulador de Wii U
GenericName[fr]=Émulateur de Wii U
GenericName[it]=Emulatore Wii U
Comment=Software to emulate Wii U games and applications on PC
Comment[fi]=Ohjelmisto Wii U -pelien ja sovellusten emulointiin PC:lla
Comment[de]=Software zum emulieren von Wii U Spielen und Anwendungen auf dem PC
Comment[ru]=Программа для эмуляции игр и приложений Wii U на PC
Comment[fr]=Application pour émuler des jeux et des applications Wii U sur PC
Comment[nl]=Applicatie om Wii U spellen en applicaties te emuleren op PC
Comment[el]=Πρόγραμμα προσομοίωσης παιχνιδιών και εφαρμογών Wii U στον υπολογιστή
Comment[es]=Software para emular juegos y aplicaciones de Wii U en PC
Comment[pt_BR]=Software para emular jogos e aplicativos de Wii U no PC
Comment[it]=Software per emulare giochi e applicazioni per Wii U su PC
Categories=Game;Emulator;
Keywords=Nintendo;
MimeType=application/x-wii-u-rom;
X-AppImage-Version=ea86c77

Contains `info.cemu.Cemu.png` in the AppImages root directory which points to `usr/share/icons/hicolor/128x128/apps/info.cemu.Cemu.png`

**Comment by dreifacherspass** [comment]
Hello! Thank you for the info.

I will have the icons ready by the next update.

The appimage files containing the info you uploaded will find the icons of your default icon theme.

Someone on pling informed me that they had issues with flatpaks. Read my answer and see if it helps (https://www.pling.com/p/1999292).

**Comment by AxerTheAxe** [comment]
Okay. Thanks a lot!
