### ISSUE TITLE
[Icon Request] Qubes OS (A Xen/Linux Distribution)

### ISSUE THREAD

**Issue by Cyanide-1** [dreifacherspass/cyberpunk-technotronic-icon-theme#7]
Hello! I like this icon pack. Could you please add Qubes OS icon to it? Information is below. 😁 Thanks!

**Information**

* **Icon Name:** distributor-logo-qubes

* **Website:** https://www.qubes-os.org/

* **Description:** "A reasonably secure operating system."

* **Reference Pictures:** https://www.qubes-os.org/doc/visual-style-guide/#logos
![qubes-logo](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/assets/136278181/b201cb54-3a29-48b9-ac8b-192bb88cd326)
![qubes-logo-2000x-2150x](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/assets/136278181/fa7f1135-10ee-4c83-b1f5-71b819f2a476)

**Comment by dreifacherspass** [comment]
You are welcome! The icon will be in the next update.

Thank you for providing the information. 

😀

**Comment by Cyanide-1** [comment]
no problem! thanks for adding the icon!! :)
