### ISSUE TITLE
Request: Pastel Folder Color?

### ISSUE THREAD

**Issue by 0pLuS0** [dreifacherspass/cyberpunk-technotronic-icon-theme#8]
Hi,

First, let me say this is an amazing looking iconset!

I guess for me, I'm so use to using/seeing solid color folders, that my eyes have a hard time adjusting/looking at folders and files in Outlines.

If you could please consider making a different look besides this one, with a color inside the folders, that would be great. Maybe a light pastel look, so it doesn't distract from the original look you've created, but maybe/hopefully something that is easy on the eyes to work with.

Here's a look at your iconset I've been trying out in SpaceFM.

![cyberpunk](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/assets/36190223/259e530d-532e-4561-ab0a-a6c7cce0d8bc)

```THANKS for your consideration, it's greatly appreciated!```

**Comment by dreifacherspass** [comment]
Hello! I am glad you like the iconse and  thank you for opening the issue.

I've created two versions of filled folders. 

Could you install the themes and tell me which you like most?

[cyberpunk-technotronic-filled-folders-1.tar.gz](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/files/12651771/cyberpunk-technotronic-filled-folders-1.tar.gz)
[cyberpunk-technotronic-filled-folders-2.tar.gz](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/files/12651772/cyberpunk-technotronic-filled-folders-2.tar.gz)

**Comment by 0pLuS0** [comment]
Hi,

Both of these look really nice, but the #2 was more of what I was thinking of, so you kept the outline to the folders, which helps it stick to something of the original look.

For me personally all the various files, text, shell scripts, etc., it's still hard for my eyes to see these in just the outlined colors.

Maybe in time, you can create more traditional looking files, but still something that has your Cyberpunk feel to it, without loosing that.

![cyberpunk-2](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/assets/36190223/cce493b0-49cc-4e4f-af64-9587e22f66d9)

THANKS a lot for taking your time to create this!

**Comment by dreifacherspass** [comment]
Your feedback is most welcome! I am glad you liked the filled-folders variant. I will upload it on pling, others may like it too!

Could you show me some examples of icons for files, text and shell scripts that are easier on the eyes? I could create a new theme.

As far as the colours are concerned, I am already creating a variant of the theme using softer, paler colours. You will find it on pling.

**Comment by AxerTheAxe** [comment]
> Your feedback is most welcome! I am glad you liked the filled-folders variant. I will upload it on pling, others may like it too!
> 
> Could you show me some examples of icons for files, text and shell scripts that are easier on the eyes? I could create a new theme.
> 
> As far as the colours are concerned, I am already creating a variant of the theme using softer, paler colours. You will find it on pling.

Will the new folders be included in a separate version of the icon theme or will they replace the current ones>

**Comment by dreifacherspass** [comment]
The new folders will be included in a separate icon theme that will depend on the main theme, so people can choose filled or outline folders. For people that like filled folders, both themes must be installed.

**Comment by AxerTheAxe** [comment]
That sounds great, thanks!

**Comment by 0pLuS0** [comment]
I'd hate to show you looks of files, to ruin your original creativity thoughts LOL...

Just consider it, think about it like, just having all the shell files, scripts, conf, text files and anything, that have more traditional looks, I'm sure that makes sense.

But at the same time, while finding a more traditional look for all of these, possibly still with a touch of cyberpunk-technotronic flair... hmm 

THANKS

**Comment by dreifacherspass** [comment]
You are welcome guys!
