### ISSUE TITLE
Godot does not always use the correct icon.

### ISSUE THREAD

**Issue by AxerTheAxe** [dreifacherspass/cyberpunk-technotronic-icon-theme#9]
Hello again, I have noticed that Godot will sometimes not use the icon from the theme on my panel. Godot will use the correct icon when I search for it in my application launcher and when the initial project overview page is open. But once you actually open a project in Godot, it will switch to a generic icon. I believe this is because the engine interface itself is a different application than the project overview greeter. Here are some images demonstrating this(Look at the icon in my panel):

Project overview when you first open Godot:
![gd1](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/assets/99703210/d46f3255-b214-47ae-9b84-bb276dff8ea2)
Engine interface when you open a project:
![gd2](https://github.com/dreifacherspass/cyberpunk-technotronic-icon-theme/assets/99703210/23668dcc-4e5a-416b-a1d4-18fbe39b3d98)

I am unsure if this is something that Godot forces that you cannot fix so sorry if that is the case but I would greatly appreciate it if you could look into this. Once again thank you very much for all of the work you put into this theme!

**Comment by dreifacherspass** [comment]
You are welcome. Thank you for your kind words and for reporting this issue.

You are right about the engine interface and the greeter.

You can fix this issue by adding this line `StartupWMClass=Godot_Engine` to your godot.desktop file. (If there is a `StartupWMClass=Godot` then delete it).

By the way, I saw that I haven't included the mimetype icons for godot. I will have them ready by the next update!

**Comment by AxerTheAxe** [comment]
Thanks a lot!
